services:
  - type: web
    name: entrepreneurial-ecosystem-survey
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /